### ISSUE TITLE
Decrypting/unlocking files on a drive other than C:\ doesn't work

### ISSUE THREAD

**Issue by evaera** [Nazgul07/BitCrypt#1]
Locking/encrypting files on drives other than C:\ works fine, but when you try to decrypt the file, it will look like it completes but the file never actually gets created in the directory. However, if there's already a file in the directory with the same name, it will ask if you want to overwrite it. Nonetheless, there's no way to decrypt the file without first copying it to a directory somewhere in C:.

**Comment by Nazgul07** [comment]
I verified this issue as well. I will have this fixed in a new release tomorrow.

**Comment by Nazgul07** [comment]
And thank you for the help!

**Comment by evaera** [comment]
no problem :blush:

**Comment by Nazgul07** [comment]
Issue has been fixed.
