### ISSUE TITLE
[FIXED] Encryption details

### ISSUE THREAD

**Issue by sergeevabc** [Nazgul07/BitCrypt#8]
Dear Mr. Correll, 
Could you be so kind to insert encryption details into readme.md, the front page?
So far we either have to examine sources or just trust that crypto is done right.
For example, eyes are looking for AES mode used, vector, etc.

**Comment by Nazgul07** [comment]
The only real way to trust that it is done right is to look in the code and verify, but I will update it anyway. 

Also, here is a shortened code snippet that is used:
var cipher = crypto.createCipher('aes-256-cbc', lockPassword),
      input = fs.createReadStream(file.path),
      output = fs.createWriteStream(destination);
input.pipe(cipher).pipe(output);


So as you can see, it uses AES 256 with CBC and a user supplied password.
